print("Opening and closing the file\n")
print("Reading characters forom the file")
text_file = open("read_it.txt", "r")
print(text_file.read(1))
print(text_file.read(5))
text_file.close()
print("")

print("reading the entire file at once")
text_file = open("read_it.txt", "r")
whole_thing = text_file.read()
print(whole_thing)
text_file.close()
print("")

print("Reading characters from a line")
text_file = open("read_it.txt", "r")
print(text_file.readline(1))
print(text_file.readline(5))
text_file.close()
print("")

print("Reading one line at a time.")
text_file = open("read_it.txt", "r")
print(text_file.readline())
print(text_file.readline())
print(text_file.readline())
text_file.close()
print("")

print("Reading the entire file into a list.")
text_file = open("read_it.txt", "r")
lines = text_file.readlines()
print(lines)
text_file.close()
print(len(lines))
text_file = open("read_it.txt", "r")
print(text_file.readline())
print(text_file.readline())
print(text_file.readline())
text_file.close()
print("")

print("Looping through the file, line by line.")
text_file = open("read_it.txt", "r")
for line in text_file:
  print(line)
text_file.close()

print("\n\nPress the enter key to exit.")
